spring:
    application:
        name: customer-service
    datasource:
        driver-class-name: org.hsqldb.jdbc.JDBCDriver
        url: jdbc:hsqldb:mem:testdb;DB_CLOSE_DELAY=-1
        username: sa
        password:
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate.format_sql: true
#    spring.rabbitmq.host=localhost
#    spring.rabbitmq.port=5672
#    spring.rabbitmq.username=guest
#    spring.rabbitmq.password=guest
#
#    rabbitmq.queue.name=knfQueue
#    rabbitmq.exchange.name=knfTopicExchange
#    rabbitmq.routing.key=knfRoutingKey
#
#    server.port=8081


server:
    port: 8200
    error:
        include-message: always
